### ISSUE TITLE
Document fails to load for Collaborator repositories

### ISSUE THREAD

**Issue by lbotinelly** [jchartrand/CWRC-GitServer#3]
## Expected Behaviour

- "Load From a Github Repository"
- "Show repositories for which I am: Collaborator"
- On List Expansion: Show repository files

## Current Behaviour

- "Load From a Github Repository"
- "Show repositories for which I am: Collaborator"
- On List Expansion: 
 - Exception. Status: 500 Internal Server Error
 - Content: { "code":403,"message":"{\"message\":\"Resource not accessible by integration\",\"documentation_url\":\"https://developer.github.com/v3/repos/branches/#get-branch\"}"} 
 - "Loading Repository Structure..." message is never replaced by content.

* Browser Name:
Chrome Version 77.0.3865.120 (Official Build) (64-bit)

* Operating System:
Windows 10 Education v. 1903

* Sources:
	https://github.com/cwrc/CWRC-GitServer		2240a37
	https://github.com/cwrc/CWRC-GitWriter		d295174

**Comment by ajmacdonald** [comment]
This issue was due to cached older versions and was resolved with a fresh install.
