### ISSUE TITLE
Document fails to load for Owner repositories

### ISSUE THREAD

**Issue by lbotinelly** [jchartrand/CWRC-GitServer#4]
## Expected Behaviour

- "Load From a Github Repository"
- "Show repositories for which I am: Owner"
- On List Expansion: Show repository files

## Current Behaviour

- "Load From a Github Repository"
- "Show repositories for which I am: Owner"
 - On List expansion: 
  - Javascript console: "react.development.js:188 Warning: Each child in a list should have a unique "key" prop." (List does visibly expands, though.)
 - On document selection:
  - Javascript console: "jquery.js:133 Uncaught Error: Invalid XML: language: node_js | node_js: - "4"" (Document fails to load)

* Browser Name:
Chrome Version 77.0.3865.120 (Official Build) (64-bit)

* Operating System:
Windows 10 Education v. 1903

* Sources:
	https://github.com/cwrc/CWRC-GitServer		2240a37
	https://github.com/cwrc/CWRC-GitWriter		d295174

**Comment by ajmacdonald** [comment]
This issue was due to cached older versions and was resolved with a fresh install.
