### ISSUE TITLE
Correction entity box empty

### ISSUE THREAD

**Issue by ilovan** [jchartrand/CWRC-GitServer#5]
## Expected Behaviour
![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/f22d51e7-09ec-4f72-af34-910394402f16)

## Current Behaviour
![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/61d92e1b-4980-459a-b247-09562c0dc5d8)

**Comment by ajmacdonald** [comment]
Issue moved to [cwrc/CWRC-WriterBase #208](https://github.com/cwrc/CWRC-WriterBase/issues/208) via [**ZenHub**](https://www.zenhub.com/)
